all:
  #hosts:
  #  192.168.1.10:
  children:
    masters:
      hosts:
        magi640:
          ansible_ssh_host: 192.168.1.200
          ansible_ssh_port: 22
          ansible_ssh_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    workers:
      hosts:
        pi_worker1:
          ansible_ssh_host: 192.168.1.201
          ansible_ssh_port: 22
          ansible_ssh_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        pi_worker2:
          ansible_ssh_host: 192.168.1.202
          ansible_ssh_port: 22
          ansible_ssh_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        pi_worker3:
          ansible_ssh_host: 192.168.1.203
          ansible_ssh_port: 22
          ansible_ssh_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
