---
- name: Update and upgrade all apt packages
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade all
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400 #One day
