---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

docker_release_channel: stable
docker_arch: arm64
#docker_repository: "deb [arch={{ docker_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_release_channel }}"
docker_repository: "deb [arch={{ docker_arch }}] https://download.docker.com/linux/ubuntu focal {{ docker_release_channel }}"
docker_ignore_key_error: true
#docker_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
docker_gpg_key: https://download.docker.com/linux/ubuntu/gpg
