version: "3"
services:

  scheduler:
    image: mario21ic/dask:arm64
    command: dask-scheduler
    ports:
      - 8786:8786
      - 8787:8787
    networks:
      - backend
    deploy:
      replicas: 1
      labels: [APP=DASK,ROLE=SCHEDULER]
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  worker:
    image: mario21ic/dask:arm64
    command: dask-worker --nthreads '2' --no-dashboard --memory-limit 6GB --death-timeout '60' scheduler:8786
    networks:
      - backend
    depends_on:
      - scheduler
    deploy:
      mode: global
      #replicas: 3
      labels: [APP=DASK,ROLE=WORKER]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      #placement:
      #  constraints: [node.role == manager]

networks:
  backend:

